#!/usr/bin/env python3
"""
启动LightRAG Server（WebUI）
"""
import os
import sys
import subprocess
from pathlib import Path

# 项目根目录
PROJECT_ROOT = Path(__file__).parent.parent

def check_dependencies():
    """检查必要的依赖"""
    try:
        import lightrag
        print("[INFO] LightRAG已安装")
    except ImportError:
        print("[ERROR] LightRAG未安装，请先安装：")
        print("  pip install 'lightrag-hku[api]'")
        sys.exit(1)
    
    # 检查前端是否已构建
    webui_dir = PROJECT_ROOT / "lightrag_webui"
    if not webui_dir.exists():
        print("[WARN] lightrag_webui目录不存在，可能需要从源码安装LightRAG")
        print("  或者前端会自动构建")

def create_env_file():
    """仅在.env文件不存在时创建默认配置文件"""
    env_file = PROJECT_ROOT / ".env"
    
    if env_file.exists():
        print(f"[INFO] .env文件已存在: {env_file}")
        print("[INFO] 将直接使用.env文件中的配置，不会修改")
        return
    
    # 默认配置（仅在文件不存在时创建）
    default_embedding_path = str(PROJECT_ROOT / "models" / "Qwen3-Embedding-8B")
    if not os.path.exists(PROJECT_ROOT / "models" / "Qwen3-Embedding-8B"):
        default_embedding_path = ""
    
    # 写入.env文件
    with open(env_file, 'w', encoding='utf-8') as f:
        f.write("# LightRAG Server Configuration\n")
        f.write("# Generated by start_lightrag_server.py\n\n")
        
        f.write("# LLM Configuration (vLLM)\n")
        # 优先使用环境变量 LLM_MODEL，如果没有则尝试检测 vLLM 实际使用的模型
        default_model = os.getenv('LLM_MODEL', '')
        if not default_model:
            # 尝试检测 vLLM 实际使用的模型路径
            import subprocess
            try:
                result = subprocess.run(
                    ["curl", "-s", "http://localhost:8000/v1/models"],
                    capture_output=True,
                    text=True,
                    timeout=2
                )
                if result.returncode == 0:
                    import json
                    models = json.loads(result.stdout)
                    if models.get("data") and len(models["data"]) > 0:
                        # 使用 vLLM 返回的模型 ID（可能是路径）
                        default_model = models["data"][0].get("id", "")
            except Exception:
                pass
        if not default_model:
            # 如果检测失败，尝试使用 VLLM_MODEL 环境变量或默认值
            default_model = os.getenv('VLLM_MODEL', '/kongweiwen/models/Qwen2.5-14B')
        f.write(f"LLM_MODEL={default_model}\n")
        default_base_url = os.getenv('VLLM_BASE_URL', 'http://localhost:8000/v1')
        # LLM_BINDING_HOST 需要包含 /v1 后缀（LightRAG Server 直接使用它作为 base_url）
        f.write(f"LLM_BASE_URL={default_base_url}\n")
        f.write(f"OPENAI_API_BASE={default_base_url}\n")
        f.write(f"OPENAI_BASE_URL={default_base_url}\n")
        f.write(f"LLM_BINDING_HOST={default_base_url}\n")
        f.write("LLM_API_KEY=empty\n")
        f.write("OPENAI_API_KEY=empty\n")
        f.write("LLM_BINDING=openai\n\n")
        
        f.write("# Embedding Configuration\n")
        # 从环境变量读取配置，如果没有则使用默认值
        embedding_model_name = os.getenv('EMBEDDING_MODEL_NAME', 'Qwen/Qwen3-Embedding-8B')
        embedding_binding = os.getenv('EMBEDDING_BINDING', 'ollama')  # 默认使用 ollama
        embedding_host = os.getenv('EMBEDDING_BINDING_HOST', 'http://localhost:11434')
        
        # 根据模型名称确定维度（Qwen3-Embedding-8B 是 4096 维）
        if 'Qwen3-Embedding-8B' in embedding_model_name or 'Qwen3-Embedding-8B' in str(default_embedding_path):
            embedding_dim = 4096
            # 如果使用 Ollama，模型名称格式需要调整
            if embedding_binding == 'ollama':
                embedding_model = 'qwen3-embedding-8b:latest'  # Ollama 模型名称格式
            else:
                embedding_model = embedding_model_name
        else:
            # 其他模型默认 1024 维（如 bge-m3, bge-large-zh-v1.5）
            embedding_dim = 1024
            embedding_model = embedding_model_name
        
        # 如果没有指定 embedding_binding_host，使用默认的 Embedding API 服务端口
        if not embedding_host or embedding_host == 'http://localhost:11434':
            if embedding_binding == 'openai':
                embedding_host = 'http://localhost:8081'  # 默认 Embedding API 端口
        
        f.write(f"EMBEDDING_BINDING={embedding_binding}\n")
        f.write(f"EMBEDDING_BINDING_HOST={embedding_host}\n")
        f.write(f"EMBEDDING_MODEL={embedding_model}\n")
        f.write(f"EMBEDDING_DIM={embedding_dim}\n")
        # 注意：vLLM 不支持 embedding API，需要设置 EMBEDDING_BINDING_HOST 指向支持 embedding 的服务
        # 例如：Ollama (http://localhost:11434) 或自定义的 embedding API 服务（如 text-embeddings-inference）
        # 如果使用本地 HuggingFace 模型，建议：
        # 1. 使用 Ollama 部署模型（推荐）
        # 2. 使用 text-embeddings-inference 创建 OpenAI-compatible API
        f.write("\n")
        
        f.write("# Working Directory\n")
        # 使用绝对路径，确保 LightRAG Server 能正确找到数据目录
        working_dir = (PROJECT_ROOT / 'data' / 'vector_db' / 'lightrag').resolve()
        f.write(f"WORKING_DIR={working_dir}\n\n")
        
        f.write("# Knowledge Graph Configuration\n")
        f.write("SUMMARY_LANGUAGE=Chinese\n")  # 设置摘要语言为中文，确保知识图谱正确显示
        f.write("KG_STORAGE_TYPE=networkx\n")  # 使用 NetworkX 存储知识图谱（默认）
        f.write("\n")
        
        f.write("# Server Configuration\n")
        f.write("HOST=0.0.0.0\n")
        f.write("PORT=9797\n")
    
    print(f"[INFO] 已创建默认配置文件: {env_file}")
    print("[INFO] 请根据需要修改.env文件中的配置")

def check_vllm():
    """检查vLLM服务是否运行"""
    import requests
    base_url = os.getenv("VLLM_BASE_URL", "http://localhost:8000/v1")
    health_url = base_url.replace("/v1", "/health")
    
    try:
        response = requests.get(health_url, timeout=5)
        if response.status_code == 200:
            print("[INFO] vLLM服务运行正常")
            return True
        else:
            print(f"[WARN] vLLM服务状态码: {response.status_code}")
            return False
    except Exception as e:
        print(f"[WARN] 无法连接到vLLM服务: {e}")
        print("请确保vLLM服务正在运行：")
        print("  python -m vllm.entrypoints.openai.api_server \\")
        print("    --model Qwen/Qwen2.5-14B-Instruct \\")
        print("    --port 8000")
        return False

def load_env_file():
    """加载.env文件中的环境变量"""
    env_file = PROJECT_ROOT / ".env"
    if env_file.exists():
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip()
                    # 设置环境变量
                    os.environ[key] = value
                    print(f"[INFO] 设置环境变量: {key}={value}")

def main():
    """主函数"""
    print("=" * 60)
    print("LightRAG Server 启动脚本")
    print("=" * 60)
    
    # 检查依赖
    check_dependencies()
    
    # 检查vLLM
    check_vllm()
    
    # 如果.env文件不存在，创建默认配置
    env_file = PROJECT_ROOT / ".env"
    if not env_file.exists():
        print("[INFO] .env文件不存在，创建默认配置...")
        create_env_file()
    
    # 加载.env文件中的环境变量（直接使用.env中的配置，不临时修改）
    load_env_file()
    
    # 检测并更新 LLM_MODEL（从 vLLM API 获取实际的模型 ID）
    if not os.environ.get('LLM_MODEL') or os.environ.get('LLM_MODEL') == 'gpt-4o-mini':
        # 尝试从 vLLM API 检测模型
        import requests
        try:
            response = requests.get('http://localhost:8000/v1/models', timeout=2)
            if response.status_code == 200:
                models = response.json()
                if models.get("data") and len(models["data"]) > 0:
                    detected_model = models["data"][0].get("id", "")
                    if detected_model:
                        os.environ["LLM_MODEL"] = detected_model
                        print(f"[INFO] 检测到 vLLM 模型: {detected_model}")
        except Exception as e:
            print(f"[WARN] 无法检测 vLLM 模型: {e}")
            # 如果检测失败，使用默认值
            if not os.environ.get('LLM_MODEL') or os.environ.get('LLM_MODEL') == 'gpt-4o-mini':
                default_vllm_model = os.getenv('VLLM_MODEL', '/kongweiwen/models/Qwen2.5-14B')
                os.environ["LLM_MODEL"] = default_vllm_model
                print(f"[INFO] 使用默认模型: {default_vllm_model}")
    
    # 确保 OPENAI_API_KEY 被设置（LightRAG Server 需要这个变量）
    # 如果 LLM_API_KEY 存在，同步到 OPENAI_API_KEY
    if "LLM_API_KEY" in os.environ and "OPENAI_API_KEY" not in os.environ:
        os.environ["OPENAI_API_KEY"] = os.environ["LLM_API_KEY"]
        print(f"[INFO] 设置 OPENAI_API_KEY: {os.environ['OPENAI_API_KEY']}")
    elif "OPENAI_API_KEY" not in os.environ:
        # 如果都没有设置，设置默认值
        os.environ["OPENAI_API_KEY"] = "empty"
        os.environ["LLM_API_KEY"] = "empty"
        print("[INFO] 设置默认 API_KEY: empty")
    
    # 确保所有可能的 OpenAI API Base URL 环境变量都被设置
    # LightRAG Server 可能使用不同的变量名，所以设置所有可能的变体
    if "LLM_BASE_URL" in os.environ:
        base_url = os.environ["LLM_BASE_URL"]
    else:
        base_url = "http://localhost:8000/v1"
        os.environ["LLM_BASE_URL"] = base_url
    
    # 设置所有可能的 OpenAI API Base URL 环境变量
    os.environ["OPENAI_API_BASE"] = base_url
    os.environ["OPENAI_BASE_URL"] = base_url
    os.environ["OPENAI_BASE"] = base_url  # 另一个可能的变体
    
    # LightRAG Server 使用 LLM_BINDING_HOST（需要包含 /v1 后缀）
    if "LLM_BINDING" in os.environ and os.environ["LLM_BINDING"] == "openai":
        # LLM_BINDING_HOST 需要包含 /v1 后缀，因为 LightRAG Server 直接使用它作为 base_url
        if "LLM_BINDING_HOST" not in os.environ:
            os.environ["LLM_BINDING_HOST"] = base_url  # 保持 /v1 后缀
            print(f"[INFO] 设置 LLM_BINDING_HOST: {os.environ['LLM_BINDING_HOST']}")
        elif not os.environ["LLM_BINDING_HOST"].endswith("/v1"):
            # 如果已设置但没有 /v1 后缀，添加它
            os.environ["LLM_BINDING_HOST"] = base_url
            print(f"[INFO] 更新 LLM_BINDING_HOST 为: {os.environ['LLM_BINDING_HOST']}")
    
    print(f"[INFO] 设置所有 OpenAI API Base URL 变量: {base_url}")
    
    # 确保 WORKING_DIR 使用绝对路径
    if "WORKING_DIR" in os.environ:
        working_dir = Path(os.environ["WORKING_DIR"]).resolve()
        os.environ["WORKING_DIR"] = str(working_dir)
        print(f"[INFO] 使用绝对路径 WORKING_DIR: {working_dir}")
    else:
        # 如果未设置，使用默认路径
        default_working_dir = (PROJECT_ROOT / 'data' / 'vector_db' / 'lightrag').resolve()
        os.environ["WORKING_DIR"] = str(default_working_dir)
        print(f"[INFO] 设置默认 WORKING_DIR: {default_working_dir}")
    
    # 确保知识图谱相关配置已设置
    if "SUMMARY_LANGUAGE" not in os.environ:
        os.environ["SUMMARY_LANGUAGE"] = "Chinese"
        print(f"[INFO] 设置 SUMMARY_LANGUAGE: Chinese（用于知识图谱显示）")
    
    # 验证必要的配置是否存在
    required_vars = ["LLM_BINDING", "EMBEDDING_BINDING", "WORKING_DIR"]
    missing_vars = [var for var in required_vars if var not in os.environ]
    if missing_vars:
        print(f"[WARN] 缺少必要的环境变量: {', '.join(missing_vars)}")
        print("[INFO] 请检查.env文件配置")
    
    # 显示配置信息（从.env文件读取的配置）
    print("\n[INFO] 当前配置（来自.env文件）:")
    print(f"  - LLM_MODEL: {os.environ.get('LLM_MODEL', '未设置')}")
    print(f"  - LLM_BASE_URL: {os.environ.get('LLM_BASE_URL', '未设置')}")
    print(f"  - OPENAI_API_BASE: {os.environ.get('OPENAI_API_BASE', '未设置')}")
    print(f"  - OPENAI_BASE_URL: {os.environ.get('OPENAI_BASE_URL', '未设置')}")
    print(f"  - LLM_BINDING: {os.environ.get('LLM_BINDING', '未设置')}")
    print(f"  - LLM_API_KEY: {os.environ.get('LLM_API_KEY', '未设置')}")
    print(f"  - OPENAI_API_KEY: {os.environ.get('OPENAI_API_KEY', '未设置')}")
    print(f"  - EMBEDDING_MODEL: {os.environ.get('EMBEDDING_MODEL', '未设置')}")
    print(f"  - EMBEDDING_MODEL_PATH: {os.environ.get('EMBEDDING_MODEL_PATH', '未设置')}")
    print(f"  - EMBEDDING_BINDING: {os.environ.get('EMBEDDING_BINDING', '未设置')}")
    print(f"  - WORKING_DIR: {os.environ.get('WORKING_DIR', '未设置')}")
    print(f"  - SUMMARY_LANGUAGE: {os.environ.get('SUMMARY_LANGUAGE', '未设置（默认：English）')}")
    print(f"  - KG_STORAGE_TYPE: {os.environ.get('KG_STORAGE_TYPE', '未设置（默认：networkx）')}")
    
    # 检查知识图谱文件是否存在
    working_dir = os.environ.get('WORKING_DIR', str((PROJECT_ROOT / 'data' / 'vector_db' / 'lightrag').resolve()))
    working_dir_path = Path(working_dir).resolve()
    
    print(f"\n[INFO] 数据目录检查:")
    print(f"  WORKING_DIR: {working_dir_path}")
    if working_dir_path.exists():
        print(f"  ✓ 目录存在")
    else:
        print(f"  ✗ 目录不存在，将创建: {working_dir_path}")
        working_dir_path.mkdir(parents=True, exist_ok=True)
    
    kg_files = [
        'vdb_entities.json',
        'vdb_relationships.json',
        'graph_chunk_entity_relation.graphml'
    ]
    print(f"\n[INFO] 知识图谱文件检查:")
    for kg_file in kg_files:
        kg_path = working_dir_path / kg_file
        if kg_path.exists():
            size = kg_path.stat().st_size
            print(f"  ✓ {kg_file} ({size/1024:.1f} KB)")
        else:
            print(f"  ✗ {kg_file} (不存在)")
    
    # 切换到项目根目录
    os.chdir(PROJECT_ROOT)
    
    # 获取服务器IP地址（用于内网访问）
    import socket
    server_ip = "localhost"  # 默认值
    try:
        # 获取本机IP地址
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        server_ip = s.getsockname()[0]
        s.close()
    except Exception:
        # 如果获取失败，尝试使用hostname
        try:
            result = subprocess.run(
                ["hostname", "-I"],
                capture_output=True,
                text=True,
                timeout=2
            )
            if result.returncode == 0 and result.stdout.strip():
                server_ip = result.stdout.strip().split()[0]
        except Exception:
            pass  # 使用默认值 localhost
    
    # 启动LightRAG Server
    print("\n[INFO] 启动LightRAG Server...")
    port = os.environ.get('PORT', '9797')
    print(f"[INFO] WebUI访问地址:")
    print(f"  - 本地访问: http://localhost:{port}")
    print(f"  - 内网访问: http://{server_ip}:{port}")
    print(f"[INFO] API文档: http://{server_ip}:{port}/docs")
    print(f"[INFO] 按 Ctrl+C 停止服务器\n")
    
    try:
        # 运行lightrag-server命令，传递当前环境变量
        env = os.environ.copy()
        subprocess.run(["lightrag-server"], check=True, env=env)
    except KeyboardInterrupt:
        print("\n[INFO] 服务器已停止")
    except FileNotFoundError:
        print("[ERROR] 找不到lightrag-server命令")
        print("请确保已安装LightRAG Server：")
        print("  pip install 'lightrag-hku[api]'")
        sys.exit(1)
    except Exception as e:
        print(f"[ERROR] 启动失败: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()

